export const newsData = [
  {
    id: 1,
    title: "Fall. Starts. Now.",
    description: "Our fall flavors are officially here. Time for all things pumpkin and pecan, including the new Pecan Oatmilk Cortado.",
    buttonText: "View the menu",
    image: "photo1.jpg",
    imageAlt: "Starbucks Frappuccino with cold foam being poured",
    backgroundColor: "beige",
    textColor: "text-gray-800",
    borderColor: "border-gray-800",
    hoverBg: "hover:bg-gray-800",
    hoverText: "hover:text-white",
    focusRing: "focus:ring-gray-800",
    imageOrder: "order-2 lg:order-1",
    textOrder: "order-1 lg:order-2",
    isSlimImage: true,
    imageAspectRatio: "aspect-[4/3]",
    lgImageAspectRatio: "lg:aspect-[16/9]",
    textPadding: "p-6 sm:p-10 lg:p-12",
    textMinHeight: "min-h-[350px] lg:min-h-[400px]",
    titleSize: "text-xl sm:text-2xl lg:text-2xl xl:text-3xl",
    descriptionSize: "text-sm sm:text-base lg:text-base",
    buttonSize: "text-xs sm:text-sm lg:text-sm"
  },
  {
    id: 2,
    title: "Super-smooth cold brews",
    description: "Savor refreshing sips of slow-steeped signature cold brew finished with Salted Caramel Cream Cold Foam or Vanilla Sweet Cream.",
    buttonText: "Order now",
    image: "photo2.jpg",
    imageAlt: "Starbucks Cold Brew",
    backgroundColor: "bg-green-950",
    textColor: "text-white",
    borderColor: "border-white",
    hoverBg: "hover:bg-white",
    hoverText: "hover:text-green-950",
    focusRing: "focus:ring-white",
    focusRingOffset: "focus:ring-offset-green-950",
    imageOrder: "order-2 lg:order-1",
    textOrder: "order-1 lg:order-2",
    isSlimImage: false,
    imageAspectRatio: "aspect-[4/3]",
    lgImageAspectRatio: "lg:aspect-square",
    textPadding: "p-8 sm:p-12 lg:p-16",
    textMinHeight: "min-h-[400px] lg:min-h-[500px]",
    titleSize: "text-xl sm:text-2xl lg:text-3xl xl:text-4xl",
    descriptionSize: "text-sm sm:text-base lg:text-lg",
    buttonSize: "text-xs sm:text-sm lg:text-base"
  },
  {
    id: 3,
    title: "Our captivating new collection",
    description: "Nigerian-American artist Shadé Akanbi blends tradition and modernity to create rich prints and patterns. For a limited time.",
    buttonText: "Shop now",
    image: "photo3.jpg",
    imageAlt: "Starbucks Collection",
    backgroundColor: "bg-amber-50",
    textColor: "text-gray-800",
    borderColor: "border-gray-800",
    hoverBg: "hover:bg-gray-800",
    hoverText: "hover:text-white",
    focusRing: "focus:ring-gray-800",
    imageOrder: "order-2 lg:order-2",
    textOrder: "order-1 lg:order-1",
    isSlimImage: true,
    imageAspectRatio: "aspect-[4/3]",
    lgImageAspectRatio: "lg:aspect-[16/9]",
    textPadding: "p-6 sm:p-10 lg:p-12",
    textMinHeight: "min-h-[350px] lg:min-h-[400px]",
    titleSize: "text-xl sm:text-2xl lg:text-2xl xl:text-3xl",
    descriptionSize: "text-sm sm:text-base lg:text-base",
    buttonSize: "text-xs sm:text-sm lg:text-sm"
  },
  {
    id: 4,
    title: "Super-smooth cold brews",
    description: "Savor refreshing sips of slow-steeped signature cold brew finished with Salted Caramel Cream Cold Foam or Vanilla Sweet Cream.",
    buttonText: "Order now",
    image: "photo4.jpg",
    imageAlt: "Starbucks Cold Brew",
    backgroundColor: "bg-green-950",
    textColor: "text-white",
    borderColor: "border-white",
    hoverBg: "hover:bg-white",
    hoverText: "hover:text-green-950",
    focusRing: "focus:ring-white",
    focusRingOffset: "focus:ring-offset-green-950",
    imageOrder: "order-2 lg:order-1",
    textOrder: "order-1 lg:order-2",
    isSlimImage: false,
    imageAspectRatio: "aspect-[4/3]",
    lgImageAspectRatio: "lg:aspect-square",
    textPadding: "p-8 sm:p-12 lg:p-16",
    textMinHeight: "min-h-[400px] lg:min-h-[500px]",
    titleSize: "text-xl sm:text-2xl lg:text-3xl xl:text-4xl",
    descriptionSize: "text-sm sm:text-base lg:text-lg",
    buttonSize: "text-xs sm:text-sm lg:text-base"
  },
  {
    id: 5,
    title: "Our captivating new collection",
    description: "Nigerian-American artist Shadé Akanbi blends tradition and modernity to create rich prints and patterns. For a limited time.",
    buttonText: "Shop now",
    image: "photo5.jpg",
    imageAlt: "Starbucks Collection",
    backgroundColor: "bg-amber-950",
    textColor: "text-white",
    borderColor: "border-white",
    hoverBg: "hover:bg-gray-800",
    hoverText: "hover:text-white",
    focusRing: "focus:ring-gray-800",
    imageOrder: "order-2 lg:order-2",
    textOrder: "order-1 lg:order-1",
    isSlimImage: true,
    imageAspectRatio: "aspect-[4/3]",
    lgImageAspectRatio: "lg:aspect-[16/9]",
    textPadding: "p-6 sm:p-10 lg:p-12",
    textMinHeight: "min-h-[350px] lg:min-h-[400px]",
    titleSize: "text-xl sm:text-2xl lg:text-2xl xl:text-3xl",
    descriptionSize: "text-sm sm:text-base lg:text-base",
    buttonSize: "text-xs sm:text-sm lg:text-sm"
  }
];